services:
  link_summary_api:    
    image: ghcr.io/dvvtech/link-summary-back:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Prod      
    networks:
      - public-network5
    secrets:
      - AiClientConfig__OpenAiApiKey
      - ProxySettings__Ip      
      - ProxySettings__Login
      - ProxySettings__Password
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.link-summary-api.rule=Host(`api.cloud-platform.pro`) && PathPrefix(`/link-summary`)"
        - "traefik.http.routers.link-summary-api.entrypoints=websecure"
        - "traefik.http.routers.link-summary-api.tls.certresolver=letsencrypt"
        - "traefik.http.services.link-summary-api.loadbalancer.server.port=8080"
        - "traefik.http.middlewares.link-summary-stripprefix.stripprefix.prefixes=/link-summary"
        - "traefik.http.routers.link-summary-api.middlewares=link-summary-stripprefix"      

networks:
  public-network5:
    external: true
    name: public-network5

secrets:
  AiClientConfig__OpenAiApiKey:
    external: true  
  ProxySettings__Ip:
    external: true
  ProxySettings__Login:
    external: true
  ProxySettings__Password:
    external: true